### ISSUE TITLE
Widget still working?

### ISSUE THREAD

**Issue by RCatersels** [ivosturm/D3Gauge#1]
Hello Ivo,

I just created a very small test project where I created the object, put a min 0 max 25 and value 10 in the object. Three sections: 0-10 10-25 and 25 to 1000. I got the result below. Am I missing something here?

Regards,

Ronald

![2017-06-16 12_01_23-mendix - homepage](https://user-images.githubusercontent.com/10200344/27222262-e032c3bc-528b-11e7-8c06-27eda556a8f7.png)

**Comment by ivosturm** [comment]
Hi Ronald, 

Should be working... Which Mendix version are you using? If it is test project, you could invite me and I could investigate.

Let me know!

**Comment by RCatersels** [comment]
Never mind already found the issue. The ranges need to add up to 100. My last range was from 25 - 1000 and then you get the above graphic. When I changed it to 100 it does work.
Thanks for your fast response.

Regards,

Ronald

![2017-06-16 13_03_06-mendix - homepage](https://user-images.githubusercontent.com/10200344/27224218-2c0f29d0-5294-11e7-81c4-c9ef31b24259.png)
