### ISSUE TITLE
The gauge doesn't render correctly when minimum value is not 0.

### ISSUE THREAD

**Issue by vinoddavis** [ivosturm/D3Gauge#2]
The gauge doesn't render correctly when minimum value is not 0. I had opened the same issue with RGraphGauge couple of days ago and it was fixed. I would appreciate if you could fix it with D3 gauge as well. Thanks in advance.

**Comment by ivosturm** [comment]
Hi vinoddavis. Indeed same issue as the RGraph Gauge. In version 1.2.1 I just released in the AppStore today it should be fixed. Can you verify and let me know?

**Comment by vinoddavis** [comment]
It works great. Thanks for the quick response.
